CREATE TABLE T_CATEGORIES (
    CATEGORY_ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    IMAGE_URL VARCHAR(500) NOT NULL
);

CREATE TABLE T_PHRASES (
    PHRASE_ID BIGSERIAL PRIMARY KEY,
    PHRASE VARCHAR(255) NOT NULL UNIQUE,
    CATEGORY_ID BIGINT REFERENCES T_CATEGORIES
);
